# spring
spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8180/
          predicates:
            - Path=/api/*/auth/**,/api/*/accout/**,/api/*/login,/api/*/signup/**
        - id: session
          uri: http://localhost:8280/
          predicates:
            - Path=/api/*/session/**

# server
server:
  title: spring-micro-gateway
  version: '@project.version@'
  port: 8080

# actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"