# spring
spring:
  application:
    name: gateway
  devtools:
    livereload:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: login
          uri: http://localhost:8180/
          predicates:
            - Path=/api/*/login,/api/*/signup/**
        - id: auth
          uri: http://localhost:8180/
          predicates:
            - Path=/api/*/auth/**,/api/*/accout/**
          filters:
            - Authentication
        - id: session
          uri: http://localhost:8280/
          predicates:
            - Path=/api/*/session/**
          filters:
            - Authentication

# server
server:
  title: spring-micro-gateway
  version: '@project.version@'
  port: 8080

# kafka
kafka:
  bootstrap:
    addresses: localhost:9092
  consumer:
    groupId: gateway

# actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"

# documentation
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# logging
logging:
  file:
    name: logs/gateway.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/gateway-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100MB
      total-size-cap: 1GB
      max-history: 7
      clean-history-on-start: false
  level:
    org:
      springframework:
        security: INFO
        cloud:
          gateway: DEBUG
    reactor:
      netty: DEBUG
    io:
      coolexplorer: DEBUG